### REST Client
###
http://localhost:4000
###
http://localhost:4000/status
###
http://localhost:4000/blocks
###
POST http://localhost:4000/blocks

{
    "message":"Mine me!"
}
###
http://localhost:4000/blocks/ac6369ed14bf5611ede4bc00f352fcd7efec92f01d052f23bf88356338999021
###
http://localhost:4000/balance/han
###
http://localhost:4000/balance/han?total=true
###
POST http://localhost:4000/transactions

{
    "to":"lee",
    "amount": 35
}
###
http://localhost:4000/mempool